In [11]:
import numpy as np
a = np.arange(9)
a = a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:

a = np.array([0,1,2,3,4,5,6,7,8,9])
for i in range (10):
    if(a[i]%2!=0):
        a[i]=-1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [22]:

x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
equal = np.array([])
greater = np.array([])
for i in range(10):
    if(x[i]==y[i]):
        equal=np.append(equal,i)
    elif(x[i]>y[i]):
        greater=np.append(greater,i)
equal,greater
        
        



(array([0.]), array([1., 2., 4., 5., 6., 7., 8., 9.]))

In [54]:
a = np.arange(100).reshape(5,-1)
print(a[0:5,0:4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [37]:

a = np.random.randint(30,41,size=10)
print(a)

[31 30 38 31 33 39 38 40 38 30]


In [53]:

A = np.arange(1,10).reshape(3,3)
B = np.array(([7,8,9],[4,5,6],[1,2,3]))

C = A+B
print("Addition : ")
print(C)

E = A-B
print("Subtraction : ")
print(E)

D = A*B
print("Product : ")
print(D)

transpose = E.T
print("Transpose : ")
print(transpose)

sum_A = np.sum(A)
print("Sum of all elements of matrix A is :",sum_A)

sum_c = np.sum(B,axis = 1)
print("Sum of each column in B : ",sum_c)

sum_r = np.sum(C,axis = 0)
print("Sum of each row in C : ",sum_r)

sor = np.sort(C,axis = None).reshape(C.shape)
print("Sorted C : ")
print(sor)




Addition : 
[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]
Subtraction : 
[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]
Product : 
[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]
Transpose : 
[[-6  0  6]
 [-6  0  6]
 [-6  0  6]]
Sum of all elements of matrix A is : 45
Sum of each column in B :  [24 15  6]
Sum of each row in C :  [24 30 36]
Sorted C : 
[[ 8  8  8]
 [10 10 10]
 [12 12 12]]
